/// Flutter icons CustomIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData account_balance_wallet = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_circle = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aries = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_downward_alt = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left_alt = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_alt = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancer = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_upward_alt = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData casino = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_bubble = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_backward = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_forward = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done_all = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData encrypted = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData format_paint = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gemini = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health_metrics = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_repair_service = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kid_star_1 = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kid_star = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_arrow_down = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData libra = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_arrow_up = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_waxing_crescent_3 = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_vert = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_horiz = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData north_east = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData progress_activity = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scorpio = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stars = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taurus = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transgender = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData virgo = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visibility_off = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visibility = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
