// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCobRe57MVlrNivDsOecFEKl-GdrQaxRMo',
    appId: '1:923729353109:web:5453a5baad75c53a3dfe9c',
    messagingSenderId: '923729353109',
    projectId: 'horoscope-mobile-app',
    authDomain: 'horoscope-mobile-app.firebaseapp.com',
    storageBucket: 'horoscope-mobile-app.appspot.com',
    measurementId: 'G-F69F2Z74R2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB3ZA2FoBp3Oqn5ID66zTA-CQqbtL0gwM',
    appId: '1:923729353109:ios:8b31d9c9b6afb9f53dfe9c',
    messagingSenderId: '923729353109',
    projectId: 'horoscope-mobile-app',
    storageBucket: 'horoscope-mobile-app.appspot.com',
    iosBundleId: 'com.example.appMobileHorosope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB3ZA2FoBp3Oqn5ID66zTA-CQqbtL0gwM',
    appId: '1:923729353109:ios:8b31d9c9b6afb9f53dfe9c',
    messagingSenderId: '923729353109',
    projectId: 'horoscope-mobile-app',
    storageBucket: 'horoscope-mobile-app.appspot.com',
    iosBundleId: 'com.example.appMobileHorosope',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCobRe57MVlrNivDsOecFEKl-GdrQaxRMo',
    appId: '1:923729353109:web:d6f5cfdfa6157b183dfe9c',
    messagingSenderId: '923729353109',
    projectId: 'horoscope-mobile-app',
    authDomain: 'horoscope-mobile-app.firebaseapp.com',
    storageBucket: 'horoscope-mobile-app.appspot.com',
    measurementId: 'G-FWDD8JZJFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsOko4i4-oqXw88Vz27RdmBd-kN9ibHmI',
    appId: '1:923729353109:android:b3716dda2cb588083dfe9c',
    messagingSenderId: '923729353109',
    projectId: 'horoscope-mobile-app',
    storageBucket: 'horoscope-mobile-app.appspot.com',
  );

}