name: horoscopix_analyzer_lints
description: A starting point for Dart libraries or applications.
version: 1.0.0


environment:
  sdk: ^3.5.1


dependencies:
  analyzer: ^6.7.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.6.7


dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

